namespace Sigil.Domain.Common;

/// <summary>
/// Base class for all domain entities with a UUID v7 primary key.
/// </summary>
public abstract class BaseEntity
{
    public Guid Id { get; set; } = Guid.NewGuid(); // UUID v7 generated by PostgreSQL
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;
}
