/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutTemplatesIndexRouteImport } from './routes/_layout/templates.index'
import { Route as LayoutLicensesIndexRouteImport } from './routes/_layout/licenses.index'
import { Route as LayoutCompaniesIndexRouteImport } from './routes/_layout/companies.index'
import { Route as LayoutTemplatesTemplateIdRouteImport } from './routes/_layout/templates.$templateId'
import { Route as LayoutLicensesLicenseIdRouteImport } from './routes/_layout/licenses.$licenseId'
import { Route as LayoutCompaniesCompanyIdRouteImport } from './routes/_layout/companies.$companyId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesIndexRoute = LayoutTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLicensesIndexRoute = LayoutLicensesIndexRouteImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompaniesIndexRoute = LayoutCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesTemplateIdRoute =
  LayoutTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLicensesLicenseIdRoute = LayoutLicensesLicenseIdRouteImport.update({
  id: '/licenses/$licenseId',
  path: '/licenses/$licenseId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompaniesCompanyIdRoute =
  LayoutCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof LayoutSettingsRoute
  '/companies/$companyId': typeof LayoutCompaniesCompanyIdRoute
  '/licenses/$licenseId': typeof LayoutLicensesLicenseIdRoute
  '/templates/$templateId': typeof LayoutTemplatesTemplateIdRoute
  '/companies/': typeof LayoutCompaniesIndexRoute
  '/licenses/': typeof LayoutLicensesIndexRoute
  '/templates/': typeof LayoutTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/companies/$companyId': typeof LayoutCompaniesCompanyIdRoute
  '/licenses/$licenseId': typeof LayoutLicensesLicenseIdRoute
  '/templates/$templateId': typeof LayoutTemplatesTemplateIdRoute
  '/companies': typeof LayoutCompaniesIndexRoute
  '/licenses': typeof LayoutLicensesIndexRoute
  '/templates': typeof LayoutTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/companies/$companyId': typeof LayoutCompaniesCompanyIdRoute
  '/_layout/licenses/$licenseId': typeof LayoutLicensesLicenseIdRoute
  '/_layout/templates/$templateId': typeof LayoutTemplatesTemplateIdRoute
  '/_layout/companies/': typeof LayoutCompaniesIndexRoute
  '/_layout/licenses/': typeof LayoutLicensesIndexRoute
  '/_layout/templates/': typeof LayoutTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/companies/$companyId'
    | '/licenses/$licenseId'
    | '/templates/$templateId'
    | '/companies/'
    | '/licenses/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/companies/$companyId'
    | '/licenses/$licenseId'
    | '/templates/$templateId'
    | '/companies'
    | '/licenses'
    | '/templates'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/companies/$companyId'
    | '/_layout/licenses/$licenseId'
    | '/_layout/templates/$templateId'
    | '/_layout/companies/'
    | '/_layout/licenses/'
    | '/_layout/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates/': {
      id: '/_layout/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof LayoutTemplatesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/licenses/': {
      id: '/_layout/licenses/'
      path: '/licenses'
      fullPath: '/licenses/'
      preLoaderRoute: typeof LayoutLicensesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/companies/': {
      id: '/_layout/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof LayoutCompaniesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates/$templateId': {
      id: '/_layout/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof LayoutTemplatesTemplateIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/licenses/$licenseId': {
      id: '/_layout/licenses/$licenseId'
      path: '/licenses/$licenseId'
      fullPath: '/licenses/$licenseId'
      preLoaderRoute: typeof LayoutLicensesLicenseIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/companies/$companyId': {
      id: '/_layout/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof LayoutCompaniesCompanyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCompaniesCompanyIdRoute: typeof LayoutCompaniesCompanyIdRoute
  LayoutLicensesLicenseIdRoute: typeof LayoutLicensesLicenseIdRoute
  LayoutTemplatesTemplateIdRoute: typeof LayoutTemplatesTemplateIdRoute
  LayoutCompaniesIndexRoute: typeof LayoutCompaniesIndexRoute
  LayoutLicensesIndexRoute: typeof LayoutLicensesIndexRoute
  LayoutTemplatesIndexRoute: typeof LayoutTemplatesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCompaniesCompanyIdRoute: LayoutCompaniesCompanyIdRoute,
  LayoutLicensesLicenseIdRoute: LayoutLicensesLicenseIdRoute,
  LayoutTemplatesTemplateIdRoute: LayoutTemplatesTemplateIdRoute,
  LayoutCompaniesIndexRoute: LayoutCompaniesIndexRoute,
  LayoutLicensesIndexRoute: LayoutLicensesIndexRoute,
  LayoutTemplatesIndexRoute: LayoutTemplatesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
